name: MCPL
version: '${project.version}'
main: me.ipincamp.mcpl.Mcpl
api-version: 1.17
authors: [ ipincamp ]
description: Minecraft plugin to make your server more fun
website: https://github.com/ipincamp/mcpl
