name: FirstPlugin
main: me.ipincamp.FirstPlugin
description: First Minecraft Plugins
version: 1.0-SNAPSHOT
authors:
  - andhra21231
  - ipincamp
api-version: 1.17

commands:
  feed:
    description: Feed your player with some food
    permission: mcpl.command.feed
    usage: /feed
  heal:
    description: Heal your player
    permission: mcpl.command.heal
    aliases:
      - buff
    usage: /heal
  spawn:
    description: Remember the last locations
    permission: mcpl.command.spawn.set
    usage: /setspawn